### ISSUE TITLE
Using srcset generates error: "Cannot use object of type K2Image as array"

### ISSUE THREAD

**Issue by kbrookes** [kricore/K2-V3-templates#1]
I found this while using the new default itemlist_item.php in the search.php layout.

When searching, that error occurs, referencing line 92 of item.php.

It could be a setup issue tho - I don't fully understand how to implement srcsets.

**Comment by kricore** [comment]
Hey there,

I made a typo it should be echo $this->item->images['xsmall'] instead of echo $this->item->image['xsmall']

Just make sure these values have (xsmall, small, large etc) the same name as the image sizes in your K2 image sizes list.
