### ISSUE TITLE
Restricting mod_k2_tools to searching just one category

### ISSUE THREAD

**Issue by kbrookes** [kricore/K2-V3-templates#4]
In the past we could modify the form action of mod_k2_tools search.php to a specific category.

For example, I could restrict search to this itemID with this action:

<?php echo JRoute::_('index.php?option=com_k2&view=itemlist&task=search&Itemid=128'); ?>

This no longer works in V3 - do you know if there's a workaround yet?

**Comment by kricore** [comment]
This is posting to a specific menu item, not a category.
In version 3 you can create a new search menu item so this is not needed anymore.
Finally the options to search into specific categories is located in mod_k2_tools' parameters.

**Comment by kbrookes** [comment]
Understood re: menu item code.

I can see the K2 Search option when creating a new menu item, but there is no option to select a menu item:

https://www.dropbox.com/s/q2jevyfpfstudhw/Screenshot%202015-09-23%2006.41.16.png?dl=0

I'll address the category restriction in mod_k2_tools over on the K3 dev github as this isn't working.
