### ISSUE TITLE
Map extrafield error

### ISSUE THREAD

**Issue by kewwel** [kricore/K2-V3-templates#5]
Hello, I am using for testing the extra field map.
I could not make it work with a new location. I put assets folder and js used in the template, uncommented the line in the output, but gives error. I recorded this video.
http://screencast-o-matic.com/watch/coQT2DfLIl
 As I go wrong?

No way to get the address other than by latitude and longitude? 
I have an idea to make directory with k2 and would be faster, you enter the address of which in latitude.

I know that here is just an example, but unfortunately do not know programming yet.

**Comment by kricore** [comment]
You need to remove the <?php ?> brackets alongside with the /\* comments. This is causing the error.

This is a rudimentary field made to serve as an example.
You can enhance it to look for an address as well.

The HTML5 way will simply let you embed the map with a more versatile and efficient way than the iframe.
In order not to get two maps you should kill the iframe. Finally if you want to add multiple maps in one page you should move this file (css+js) into your template. If you do this, you need to update these links so you won't 404 errors.

**Comment by kewwel** [comment]
Thanks for answering me. I did as you said, but it did not work with me. Then I noticed well iframe Bing and customizei to Google Maps, so it worked.
http://screencast-o-matic.com/watch/coQTqhfL0e

**Comment by kricore** [comment]
Nice to hear that Kewwel.
I 'm glad it worked  :)
