### ISSUE TITLE
Use meta tag & title code in cheatsheet results in two sets of title & meta tags

### ISSUE THREAD

**Issue by kbrookes** [kricore/K2-V3-templates#6]
Hey there,

So because K2v3 doesn't play nice with sh404SEF, I've needed to look for an alternative method of dealing with setting explicit title tags and meta descriptions and thought I'd try the version in the cheatsheet. (I'm setting meta descriptions via extra fields because it makes sense to set both the title and the description in the same place).

It works, in so far as the title tag and meta description tag appear in the head, but they appear below the existing, default title and meta descriptions and the first ones take precedence.

So is there a way to allow the system to set the title and meta tags only if we haven't explicitly set them in extraFields?

**Comment by kbrookes** [comment]
Solved my own question - adding it here in case it helps someone else:

Setting the title and description using the addCustomTag does work, but duplicates existing tags.

What we want is to replace existing tags where appropriate.

The correct code to do this is:

$doc = JFactory::getDocument();
$doc->setTitle($this->item->extraFields->titletag->value);
$doc->setMetaData('description', $this->item->extraFields->metadescription->value);

(assuming that 'titletag' and 'metadescription' are your extrafield names)

**Comment by kbrookes** [comment]
Another quick update - it's worth having a check to see if the extraField is in use:

$doc = JFactory::getDocument();
if($this->item->extraFields->titletag->value != ''):
    $doc->setTitle($this->item->extraFields->titletag->value);
endif; 
if($this->item->extraFields->metadescription->value != ''):
    $doc->setMetaData('description', $this->item->extraFields->metadescription->value);
endif;

**Comment by kricore** [comment]
You 're right, I'll add the check to the repo.
Thanks :+1:

**Comment by kbrookes** [comment]
No problem at all.

There's some useful stuff in the document I found to get the right title
and metaTag settings (https://api.joomla.org/cms-3/classes/JDocument.html).

It looks like developers could take this further and create their own
mini-SEF solution within K2. For example, this setting:

setLink(string $url) : \JDocument

That allows you to set the document link. I'd imagine that would mean that
could create your own URLs via an extraField.

Cool stuff.

**Comment by SpyrosJonas** [comment]
Hi we also experience the same problem we have June 16th, 2014 - Version 2.7.0.
The code that you mention where should we place it.
We have tried in the public_html/components/com_k2/views/item/view.html.php but did not work.
I would appreciate if you could let us know where to place the code.
Thanking you in advance

**Comment by kricore** [comment]
Hello buddy, wrong repo :)
This repo contains template related stuff only. 

Kelsey was adding an new meta description based on an extrafield.
https://github.com/kricore/Advanced-templating-with-K2/blob/master/_inc/cheatsheet.php#L112-L120

You should address this issue to K2's community forum.
